module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    USER_ADD_NEW: "USER_ADD_NEW",
    ADD_COMMENT: "ADD_COMMENT",
    ASSIGN_TICKET: "ASSIGN_TICKET",
    TICKET_STATUS_UPDATE: "TICKET_STATUS_UPDATE",
    TICKET_ADD_NEW: "TICKET_ADD_NEW",
    TICKET_UPDATE: "TICKET_UPDATE",
    RIGHT_DRAWER_TYPES: "RIGHT_DRAWER_TYPES",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
    USER_DELETE: "USER_DELETE",
  },
});
